export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_SELECT_CATE = "SET_SELECT_CATE";
export const DELETE_SELECT_CATE = "DELETE_SELECT_CATE";