export const GET_ALL_STORE = "GET_ALL_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const ADD_STORE = "ADD_STORE";
export const SET_SELECT_STORE = "SET_SELECT_STORE";
export const ADD_DETAIL_STORE = "ADD_DETAIL_STORE";
export const UPDATE_DETAIL_STORE = "UPDATE_DETAIL_STORE";
export const DELETE_DETAIL_STORE = "ADD_DETAIL_STORE";